# Generated by Django 3.1.4 on 2020-12-27 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Textul ce apare la inceputul intrebarii."
                    ),
                ),
                (
                    "number",
                    models.IntegerField(help_text="Pozitia pe pagina a intrebarii"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuestionPage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.IntegerField(
                        help_text="Field pentru pastrat ordinea paginilor", unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FillInQuestion",
            fields=[
                (
                    "question_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="chestionar.question",
                    ),
                ),
                ("answer", models.TextField(help_text="Raspunsul primit")),
            ],
            bases=("chestionar.question",),
        ),
        migrations.CreateModel(
            name="MultipleChoiceQuesition",
            fields=[
                (
                    "question_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="chestionar.question",
                    ),
                ),
                ("choice_1", models.TextField(help_text="Valoarea 1")),
                ("choice_2", models.TextField(help_text="Valoarea 2")),
                ("choice_3", models.TextField(help_text="Valoarea 3")),
            ],
            bases=("chestionar.question",),
        ),
        migrations.CreateModel(
            name="MultipleSelectQuestion",
            fields=[
                (
                    "question_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="chestionar.question",
                    ),
                ),
                ("option_1", models.TextField(help_text="Optiunea 1")),
                ("option_2", models.TextField(help_text="Optiunea 2")),
                ("option_3", models.TextField(help_text="Optiunea 3")),
            ],
            bases=("chestionar.question",),
        ),
        migrations.AddField(
            model_name="question",
            name="page",
            field=models.ForeignKey(
                help_text="Pagina pe care apare aceasta intrebare",
                on_delete=django.db.models.deletion.CASCADE,
                to="chestionar.questionpage",
            ),
        ),
    ]
